services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_ci:/var/lib/postgresql/data
    networks:
      - conversa

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        REQUIREMENTS_FILE: requirements/dev.txt
    command: >
      sh -c "python manage.py migrate &&
             python manage.py test"
    env_file: []  # <- Écrase le env_file du base
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_SECRET_KEY: dummy
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_DB_NAME: conversadb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: $DJANGO_DB_PASSWORD
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
    depends_on:
      - db
    networks:
      - conversa

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
      target: build
    env_file: []  # <- Pour éviter aussi la même erreur
    networks:
      - conversa

volumes:
  postgres_data_ci:

networks:
  conversa:
    external: true
